### ISSUE TITLE
windows release missing in v0.2.0

### ISSUE THREAD

**Issue by kasparinho** [elixir-nx/xla#14]
Hi @jonatanklosko 

i am trying to get started with exla on my windows machine.

is there a reason why v0.2.0 release is not available for windows?

thank you for your effort

best regards,
kaspar

**Comment by jonatanklosko** [comment]
Hey @kasparinho! Unfortunately EXLA doesn't support Windows at the moment. We extracted the heavy XLA dependency to this repository, so that we can provide precompiled version of that and save on installation time, however we hard trouble integrating this setup on Windows. I don't think there were many requests for Windows support, so we didn't prioritize this.

For now I'd recommend using WSL or working with Nx in Docker.

**Comment by kasparinho** [comment]
Thank you so much for the quick reply. 

I will try WSL then
