### ISSUE TITLE
Include xla version on the xla downloaded archive and move it to tmp

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/xla#5]
Otherwise we can update the XLA version, but the archive will still be there with the correct architecture, which means a new one won't be downloaded.

Somewhat related, we could also store XLA archives no System.tmp_dir, this means they can be reused across projects instead of downloading every time (for example, instead of downloading them for every notebook).

**Comment by jonatanklosko** [comment]
> Otherwise we can update the XLA version, but the archive will still be there with the correct architecture, which means a new one won't be downloaded.

Currently the archives reside in `deps/xla/cache`, updating XLA would get rid of `deps/xla` and consequently remove the no longer matching archives.

> Somewhat related, we could also store XLA archives no System.tmp_dir, this means they can be reused across projects instead of downloading every time (for example, instead of downloading them for every notebook).

I was wondering if that's something we should do, but then I realised `Mix.install` already handles caching, so the most common case is pretty much handled. Still, this may help to save some space/time, but in that case we don't want to use `System.tmp_dir`, because on linux it's cleared often, so we should use a similar location to Mix. We can use version as the namespace, so it would be something like `~/.cache/xla/v0.1.0/cache/downloads/xla_extension-x86_64-linux-tpu.tar.gz`, wdyt?

**Comment by josevalim** [comment]
Path dependencies and git dependencies do not clean up deps/xla on updates. :) going with ~/.cache also works for me!
