### ISSUE TITLE
MUSL precompiled binaries?

### ISSUE THREAD

**Issue by feynmanliang** [elixir-nx/xla#72]
Hi, first thank you for your work maintaining this project!

I saw that musl ABI precompiled binaries were dropped in 0.5.0. Unfortunately, due to security we depend on the `alpine` distro images in https://hub.docker.com/r/hexpm/elixir/ that use musl libc. Is it possible to provide these precompiled binaries again, or share some possible workarounds? Thank you!

**Comment by seanmor5** [comment]
I have been down the precompiled alpine route before and it is really not fun. We had to patch TensorFlow and LLVM to get it to work previously, which wasn't really sustainable long term, and it actually never worked on arm machines.

That said it may be possible and easier now that we depend on OpenXLA instead of TensorFlow. I can take a look, but I would say if you are using arm machines it will probably not be possible because of this issue: https://github.com/bazelbuild/bazel/issues/17220

**Comment by feynmanliang** [comment]
Yes, I am coming across the pile of TF + musl compatibility issues on the internet now. Thanks for sharing.
